### ISSUE TITLE
關於目錄文件批量下載 About batch download of catalog files

### ISSUE THREAD

**Issue by Electr0Whale** [catkitchen721/ux.getuploader_downloader#1]
在巴哈姆特上看到您的帖子，於是嘗試了下，軟件很好用！但是有沒有辦法批量下載如https://ux.getuploader.com/e2339999zp/ranking/weekly/1這種目錄式的文件？
I saw your post on Bahamut, so I tried your software, it works very well! But is there a way to batch download directory-style files such as https://ux.getuploader.com/e2339999zp/ranking/weekly/1?

**Comment by catkitchen721** [comment]
@Epifall Did you mean that you want to download whole files of ranking board? Indeedly the indexes of ranking board is out of order, I will try to add this function, thank you for your feedback!
請問您的意思是想要下載整個月排行榜的檔案嗎，這些檔案的確在排行榜中編號都是亂序的，我會試著加上這個功能，謝謝你的意見！

**Comment by Electr0Whale** [comment]
是的！感谢！

**Comment by catkitchen721** [comment]
@Epifall 已發布 pre-relaese 版本，歡迎試用，目前僅支援 CLI 版本
